# Generated by Django 5.2.6 on 2025-09-21 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('metric', models.CharField(choices=[('high_risk_percentage', 'High Risk Percentage'), ('severe_count', 'Severe Cases Count'), ('completion_rate', 'Assessment Completion Rate'), ('users_needing_counselling', 'Users Needing Counselling')], max_length=50)),
                ('comparison', models.CharField(choices=[('gt', 'Greater Than'), ('lt', 'Less Than'), ('eq', 'Equals')], max_length=2)),
                ('threshold_value', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('email_recipients', models.TextField(blank=True, help_text='Comma-separated email addresses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.questionnaire')),
            ],
            options={
                'verbose_name_plural': 'Alert Thresholds',
            },
        ),
        migrations.CreateModel(
            name='DashboardAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('message', models.TextField()),
                ('current_value', models.FloatField()),
                ('threshold_value', models.FloatField()),
                ('date', models.DateField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.questionnaire')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('threshold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='wellness_dashboard.alertthreshold')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('institution_name', models.CharField(blank=True, help_text='Institution identifier', max_length=200)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0, help_text='Users who took assessment in last 30 days')),
                ('total_assessments', models.PositiveIntegerField(default=0)),
                ('users_needing_counselling', models.PositiveIntegerField(default=0)),
                ('users_high_stress', models.PositiveIntegerField(default=0)),
                ('users_poor_sleep', models.PositiveIntegerField(default=0)),
                ('users_depression_risk', models.PositiveIntegerField(default=0)),
                ('users_anxiety_risk', models.PositiveIntegerField(default=0)),
                ('avg_assessments_per_user', models.FloatField(default=0.0)),
                ('completion_rate', models.FloatField(default=0.0, help_text='Percentage of started assessments completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Institution Metrics',
                'ordering': ['-date', 'institution_name'],
                'unique_together': {('date', 'institution_name')},
            },
        ),
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_assessments', models.PositiveIntegerField(default=0)),
                ('completed_assessments', models.PositiveIntegerField(default=0)),
                ('minimal_count', models.PositiveIntegerField(default=0)),
                ('mild_count', models.PositiveIntegerField(default=0)),
                ('moderate_count', models.PositiveIntegerField(default=0)),
                ('moderately_severe_count', models.PositiveIntegerField(default=0)),
                ('severe_count', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('median_score', models.FloatField(blank=True, null=True)),
                ('high_risk_percentage', models.FloatField(default=0.0, help_text='Percentage needing professional help')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.questionnaire')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Metrics',
                'ordering': ['-date', 'questionnaire'],
                'unique_together': {('date', 'questionnaire')},
            },
        ),
    ]
