# Generated by Django 5.2.6 on 2025-09-21 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('likert', 'Likert Scale (0-3 or 0-4)'), ('boolean', 'Yes/No'), ('multiple_choice', 'Multiple Choice'), ('rating', 'Rating Scale')], default='likert', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['questionnaire', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('questionnaire_type', models.CharField(choices=[('PHQ9', 'PHQ-9 (Depression)'), ('GAD7', 'GAD-7 (Anxiety)'), ('SQI', 'Sleep Quality Index'), ('PSS', 'Perceived Stress Scale'), ('DASS21', 'DASS-21 (Depression, Anxiety, Stress)')], max_length=10)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_score', models.IntegerField(default=0)),
                ('scoring_ranges', models.JSONField(default=dict, help_text='JSON field storing score ranges for each severity level')),
            ],
            options={
                'verbose_name_plural': 'Questionnaires',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.question')),
            ],
            options={
                'ordering': ['question', 'order'],
                'unique_together': {('question', 'order')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.questionnaire'),
        ),
        migrations.CreateModel(
            name='UserAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('severity_level', models.CharField(blank=True, max_length=20)),
                ('session_info', models.JSONField(blank=True, default=dict, help_text='Browser, IP, etc.')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Assessments',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('questionnaire', 'order')},
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.userassessment')),
            ],
            options={
                'ordering': ['assessment', 'question__order'],
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
