# Generated by Django 5.2.6 on 2025-09-10 09:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Code must contain only uppercase letters and numbers')])),
                ('institution_type', models.CharField(choices=[('college', 'College'), ('university', 'University'), ('technical', 'Technical Institute'), ('medical', 'Medical College'), ('arts', 'Arts College'), ('commerce', 'Commerce College'), ('other', 'Other')], max_length=20)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('primary_color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('custom_css', models.TextField(blank=True, help_text='Additional CSS for customization')),
                ('enable_ai_support', models.BooleanField(default=True)),
                ('enable_peer_support', models.BooleanField(default=True)),
                ('enable_offline_booking', models.BooleanField(default=True)),
                ('enable_anonymous_mode', models.BooleanField(default=True)),
                ('working_hours_start', models.TimeField(default='09:00')),
                ('working_hours_end', models.TimeField(default='17:00')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LanguageSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
                ('language_code', models.CharField(help_text="ISO language code (e.g., 'hi' for Hindi)", max_length=5)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('ui_translations', models.JSONField(default=dict, help_text='UI text translations')),
                ('content_translations', models.JSONField(default=dict, help_text='Content translations')),
            ],
            options={
                'ordering': ['language_name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('primary_language', models.CharField(default='English', max_length=50)),
                ('cultural_context', models.JSONField(default=dict, help_text='Store cultural preferences, customs, festivals, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('room_location', models.CharField(blank=True, max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_profile', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselors', to='accounts.institution')),
                ('languages', models.ManyToManyField(blank=True, to='accounts.languagesupport')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='OfflineSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='accounts.counselor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offline_tickets', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_tickets', to='accounts.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='languagesupport',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_languages', to='accounts.region'),
        ),
        migrations.AddField(
            model_name='institution',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.region'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=True)),
                ('show_in_peer_support', models.BooleanField(default=False)),
                ('cultural_preferences', models.JSONField(default=dict, help_text="User's cultural preferences and sensitivities")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.institution')),
                ('preferred_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.languagesupport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounselorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_online', models.BooleanField(default=False)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.counselor')),
            ],
            options={
                'ordering': ['counselor', 'weekday', 'start_time'],
                'unique_together': {('counselor', 'weekday', 'start_time', 'end_time')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='languagesupport',
            unique_together={('language_code', 'region')},
        ),
    ]
