# Generated by Django 5.2.6 on 2025-09-22 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GAD7Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session ID for anonymous users', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('q1_nervous', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Feeling nervous, anxious, or on edge')),
                ('q2_control_worry', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Not being able to stop or control worrying')),
                ('q3_worry_much', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Worrying too much about different things')),
                ('q4_trouble_relaxing', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Trouble relaxing')),
                ('q5_restless', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text="Being so restless that it's hard to sit still")),
                ('q6_irritable', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Becoming easily annoyed or irritable')),
                ('q7_afraid', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Feeling afraid as if something awful might happen')),
                ('total_score', models.IntegerField(default=0)),
                ('severity_level', models.CharField(choices=[('minimal', 'Minimal (0-4)'), ('mild', 'Mild (5-9)'), ('moderate', 'Moderate (10-14)'), ('severe', 'Severe (15-21)')], max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GAD-7 Assessment Result',
                'verbose_name_plural': 'GAD-7 Assessment Results',
            },
        ),
        migrations.CreateModel(
            name='GHQResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session ID for anonymous users', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('q1_concentration', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text="Been able to concentrate on whatever you're doing")),
                ('q2_sleep_loss', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Lost much sleep over worry')),
                ('q3_useful_role', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Felt that you are playing a useful part in things')),
                ('q4_decision_making', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Felt capable of making decisions about things')),
                ('q5_strain', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Felt constantly under strain')),
                ('q6_problems', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text="Felt you couldn't overcome your difficulties")),
                ('q7_enjoyment', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Been able to enjoy your normal day-to-day activities')),
                ('q8_face_problems', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Been able to face up to your problems')),
                ('q9_unhappy', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Been feeling unhappy and depressed')),
                ('q10_confidence', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Been losing confidence in yourself')),
                ('q11_worthless', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Been thinking of yourself as a worthless person')),
                ('q12_happiness', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Been feeling reasonably happy, all things considered')),
                ('total_score', models.IntegerField(default=0)),
                ('severity_level', models.CharField(choices=[('low_risk', 'Low Risk (0-15)'), ('moderate_risk', 'Moderate Risk (16-20)'), ('high_risk', 'High Risk (21-36)')], max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GHQ-12 Assessment Result',
                'verbose_name_plural': 'GHQ-12 Assessment Results',
            },
        ),
        migrations.CreateModel(
            name='PHQ9Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session ID for anonymous users', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('q1_interest', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Little interest or pleasure in doing things')),
                ('q2_mood', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Feeling down, depressed, or hopeless')),
                ('q3_sleep', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Trouble falling/staying asleep or sleeping too much')),
                ('q4_energy', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Feeling tired or having little energy')),
                ('q5_appetite', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Poor appetite or overeating')),
                ('q6_self_worth', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Feeling bad about yourself')),
                ('q7_concentration', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Trouble concentrating')),
                ('q8_movement', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Moving or speaking slowly/restlessly')),
                ('q9_self_harm', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text='Thoughts of being better off dead or hurting yourself')),
                ('total_score', models.IntegerField(default=0)),
                ('severity_level', models.CharField(choices=[('minimal', 'Minimal (0-4)'), ('mild', 'Mild (5-9)'), ('moderate', 'Moderate (10-14)'), ('moderately_severe', 'Moderately Severe (15-19)'), ('severe', 'Severe (20-27)')], max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PHQ-9 Assessment Result',
                'verbose_name_plural': 'PHQ-9 Assessment Results',
            },
        ),
        migrations.CreateModel(
            name='ComprehensiveAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session ID for anonymous users', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gad7_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mental_health_platform.gad7result')),
                ('ghq_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mental_health_platform.ghqresult')),
                ('phq9_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mental_health_platform.phq9result')),
            ],
            options={
                'verbose_name': 'Comprehensive Assessment',
                'verbose_name_plural': 'Comprehensive Assessments',
            },
        ),
    ]
