# Generated by Django 5.2.6 on 2025-09-22 19:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=100, null=True)),
                ('mood', models.CharField(choices=[('happy', '😊 Happy'), ('sad', '😢 Sad'), ('angry', '😡 Angry'), ('tired', '😴 Tired'), ('anxious', '😨 Anxious')], max_length=20)),
                ('note', models.TextField(help_text='How are you feeling today?', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_analyzed', models.BooleanField(default=False)),
                ('ai_insights', models.JSONField(blank=True, help_text='AI-generated insights about mood patterns', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Journal Entry',
                'verbose_name_plural': 'Mood Journal Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
