# Generated by Django 5.2.6 on 2025-09-22 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_platform', '0002_moodentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=100, null=True)),
                ('sleep_date', models.DateField(help_text='Date of sleep (when you went to bed)')),
                ('bedtime', models.TimeField(help_text='What time did you go to bed?')),
                ('sleep_time', models.TimeField(blank=True, help_text='What time did you fall asleep?', null=True)),
                ('wake_time', models.TimeField(help_text='What time did you wake up?')),
                ('duration_hours', models.FloatField(help_text='Total sleep duration in hours')),
                ('quality', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Fair'), (4, 'Good'), (5, 'Excellent')], help_text='How would you rate your sleep quality?')),
                ('time_to_fall_asleep', models.IntegerField(blank=True, help_text='Minutes it took to fall asleep', null=True)),
                ('times_woken', models.IntegerField(default=0, help_text='How many times did you wake up?')),
                ('feeling_rested', models.BooleanField(default=True, help_text='Did you feel rested when you woke up?')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about your sleep', max_length=500)),
                ('screen_time_before_bed', models.BooleanField(default=False, help_text='Did you use screens within 1 hour before bed?')),
                ('caffeine_intake', models.BooleanField(default=False, help_text='Did you consume caffeine in the evening?')),
                ('exercise_today', models.BooleanField(default=False, help_text='Did you exercise today?')),
                ('stress_level', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Stress level (1-5)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_analyzed', models.BooleanField(default=False)),
                ('ai_insights', models.JSONField(blank=True, help_text='AI-generated sleep insights', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sleep Entry',
                'verbose_name_plural': 'Sleep Entries',
                'ordering': ['-sleep_date', '-created_at'],
                'unique_together': {('user', 'sleep_date')},
            },
        ),
    ]
