# Generated by Django 5.2.6 on 2025-09-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='bio',
            field=models.TextField(blank=True, default='Experienced mental health counselor'),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='languages',
            field=models.CharField(blank=True, default='English', help_text='e.g., English, Hindi, Tamil', max_length=200),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='specialization',
            field=models.CharField(blank=True, default='General Counseling', help_text='e.g., Anxiety, Depression, Stress Management', max_length=200),
        ),
    ]
