# Generated by Django 5.2.6 on 2025-09-21 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class or emoji', max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code', max_length=7)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Recommendation Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendation_type', models.CharField(choices=[('exercise', 'Exercise & Movement'), ('breathing', 'Breathing Exercise'), ('meditation', 'Meditation'), ('sleep', 'Sleep Hygiene'), ('nutrition', 'Nutrition'), ('social', 'Social Connection'), ('professional', 'Professional Help'), ('activity', 'Activity/Hobby'), ('mindfulness', 'Mindfulness'), ('education', 'Educational Resource')], max_length=20)),
                ('urgency', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent - Seek Professional Help')], default='medium', max_length=10)),
                ('instructions', models.TextField(blank=True, help_text='Step-by-step instructions')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated time in minutes', null=True)),
                ('external_url', models.URLField(blank=True, help_text='Link to external resource')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or other video URL')),
                ('min_score', models.IntegerField(blank=True, help_text='Minimum score to show this recommendation', null=True)),
                ('max_score', models.IntegerField(blank=True, help_text='Maximum score to show this recommendation', null=True)),
                ('severity_levels', models.JSONField(default=list, help_text='List of severity levels this applies to')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_questionnaires', models.ManyToManyField(blank=True, to='assessments.questionnaire')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.recommendationcategory')),
            ],
            options={
                'ordering': ['urgency', 'category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_level', models.CharField(max_length=20)),
                ('template_text', models.TextField(help_text='Use {{username}}, {{score}}, etc. for personalization')),
                ('is_active', models.BooleanField(default=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.questionnaire')),
            ],
            options={
                'verbose_name_plural': 'Recommendation Templates',
                'unique_together': {('questionnaire', 'severity_level')},
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('viewed', 'Viewed'), ('started', 'Started'), ('completed', 'Completed'), ('dismissed', 'Dismissed'), ('bookmarked', 'Bookmarked')], default='suggested', max_length=20)),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='1-5 star rating', null=True)),
                ('feedback', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='assessments.userassessment')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Recommendations',
                'ordering': ['-suggested_at'],
                'unique_together': {('user', 'recommendation', 'assessment')},
            },
        ),
    ]
